---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/11/5 19:35
---

local Panel_DuiZhanDaTing_MapItem = Class("Panel_DuiZhanDaTing_MapItem")

function Panel_DuiZhanDaTing_MapItem:ctor(GoParam, uitableParam, dataParam)
    self.Go = GoParam
    self.uitable = uitableParam
    self.data = dataParam

    self.uitable.ImagePro_MapBg:SetImage(self.data.MapSelectBg)         --背景
    self.uitable.Text_MapName.text = self.data.MapName      --地图名字
    self.uitable.Text_MapStar.text = self.data.MapStar      --地图星级

    --设置驾照
    if self.data.License > DataManager.GetPlayerInfo().License then
        self.uitable.ImagePro_Lock.gameObject:SetActive(true)
        self.uitable.Text_License.text = self.data.LicenseExplain
    else
        self.uitable.ImagePro_Lock.gameObject:SetActive(false)
    end

end

return Panel_DuiZhanDaTing_MapItem