---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/10/21 16:33
---

local BaseUI = require("Framework/Base/BaseUI")

local MainSceneUI = Class("MainSceneUI", BaseUI)

--暂存变量
local GameObjectPanel
local playerIcon

function MainSceneUI:on_init(args)
    GameObjectPanel = self.panel
    playerIcon=self.uitable.Image_PlayerIcon

    self.uitable.Text_Name.text = args.name             --改 Text
    self.uitable.Text_Level.text = args.level
    LoadManager.LoadSprite_Direct( args.icon,ShowPlayerIcon)        --改 Image

    SetButtonClick(self.uitable.Button_OpenShop, self.ClickButton_OpenShop)         --按钮事件的注册
    SetButtonClick(self.uitable.Button_FromShopReturnToMain, self.ClickButton_CloseShop)
end

function MainSceneUI:ClickButton_OpenShop()
    SetGoSetActive(GameObjectPanel, "PanelContainer/ShopPanel", true)
end

function MainSceneUI:ClickButton_CloseShop()
    SetGoSetActive(GameObjectPanel, "PanelContainer/ShopPanel", false)
end

function ShowPlayerIcon(texture)
    playerIcon.sprite=texture
end

return MainSceneUI
