---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/10/22 8:52
---

tableAdd = {}
tableAdd.a = 10
tableAdd.b = 20

function tableAdd:Add(a, b)
    local result = self.a + self.b
    print(result)
end

tableA = {}
tableA.a = 555
tableA.b = 666

tableB = {}
tableB.a = 777777777
tableB.b = 888888888

classTemp = tableAdd
classTemp:Add(0, 0)