---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/10/22 8:52
---

function fun1()
    print("do one ")
    fun2()
end

function fun2()
    print("do two")
end